In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_wine

In [2]:
wine = load_wine()
X = pd.DataFrame(wine.data, columns=wine.feature_names)
y = wine.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [4]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [5]:
y_pred = model.predict(X_test)

In [6]:
acc = accuracy_score(y_pred, y_test)
confusion_matrix = confusion_matrix(y_pred, y_test)
classification_report = classification_report(y_pred, y_test)

print(f"Accuracy: {acc}")
print(f"Confusion Matrix: \n{confusion_matrix}")
print(f"Classification Report: \n{classification_report}")

Accuracy: 1.0
Confusion Matrix: 
[[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]
Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        14

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

