In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score , confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder

In [18]:
df = pd.read_csv("transaction_data.csv")
df.head()

Transaction ID Sender Account ID Receiver Account ID  Transaction Amount  \
0  TXN9520068950          ACC14994            ACC16656              495.90   
1  TXN9412011085          ACC58958            ACC32826              529.62   
2  TXN4407425052          ACC56321            ACC92481              862.47   
3  TXN2214150284          ACC48650            ACC76457             1129.88   
4  TXN4247571145          ACC60921            ACC11419              933.24   

  Transaction Type            Timestamp Transaction Status  Fraud Flag  \
0          Deposit  2025-01-17 10:14:00             Failed        True   
1       Withdrawal  2025-01-17 10:51:00            Success       False   
2       Withdrawal  2025-01-17 10:50:00             Failed       False   
3         Transfer  2025-01-17 10:56:00            Success        True   
4          Deposit  2025-01-17 10:25:00            Success        True   

  Geolocation (Latitude/Longitude) Device Used Network Slice ID  Latency (ms)  \
0             34.0522 N, -74.006 W     Desktop           Slice3            10   
1           35.6895 N, -118.2437 W      Mobile           Slice2            11   
2              48.8566 N, 2.3522 W      Mobile           Slice1             4   
3             34.0522 N, -74.006 W      Mobile           Slice3            10   
4             55.7558 N, 37.6173 W      Mobile           Slice3            20   

   Slice Bandwidth (Mbps)  PIN Code  
0                     179      3075  
1                      89      2369  
2                      53      8039  
3                     127      6374  
4                     191      8375

In [19]:
df.tail()

Transaction ID Sender Account ID Receiver Account ID  Transaction Amount  \
995  TXN7395336359          ACC79886            ACC14903             1340.76   
996  TXN2215717837          ACC95972            ACC50750              483.36   
997  TXN1676848215          ACC95938            ACC18507              199.81   
998  TXN2479413280          ACC76523            ACC95234             1341.86   
999  TXN3992032184          ACC16789            ACC21980              495.36   

    Transaction Type            Timestamp Transaction Status  Fraud Flag  \
995         Transfer  2025-01-17 10:49:00            Success       False   
996       Withdrawal  2025-01-17 11:00:00             Failed        True   
997       Withdrawal  2025-01-17 10:54:00            Success       False   
998         Transfer  2025-01-17 10:59:00            Success        True   
999         Transfer  2025-01-17 10:02:00             Failed       False   

    Geolocation (Latitude/Longitude) Device Used Network Slice ID  \
995           35.6895 N, -118.2437 W      Mobile           Slice2   
996             55.7558 N, 37.6173 W      Mobile           Slice2   
997            34.0522 N, 139.6917 W     Desktop           Slice1   
998            51.5074 N, 139.6917 W      Mobile           Slice3   
999             55.7558 N, -74.006 W      Mobile           Slice2   

     Latency (ms)  Slice Bandwidth (Mbps)  PIN Code  
995            19                     224      9766  
996            12                      56      1009  
997            14                     151      9301  
998             8                      95      4038  
999             5                     155      9888

In [20]:
df.describe()

Transaction Amount  Latency (ms)  Slice Bandwidth (Mbps)    PIN Code
count          1000.00000   1000.000000              1000.00000  1000.00000
mean            771.16529     11.688000               148.51100  5458.66600
std             411.01925      5.131958                57.78634  2603.03646
min              51.89000      3.000000                50.00000  1000.00000
25%             423.34750      7.000000                98.00000  3281.75000
50%             761.65500     12.000000               148.00000  5385.50000
75%            1122.67250     16.000000               198.25000  7535.00000
max            1497.76000     20.000000               250.00000  9999.00000

In [21]:
df.isnull()

Transaction ID  Sender Account ID  Receiver Account ID  \
0             False              False                False   
1             False              False                False   
2             False              False                False   
3             False              False                False   
4             False              False                False   
..              ...                ...                  ...   
995           False              False                False   
996           False              False                False   
997           False              False                False   
998           False              False                False   
999           False              False                False   

     Transaction Amount  Transaction Type  Timestamp  Transaction Status  \
0                 False             False      False               False   
1                 False             False      False               False   
2                 False             False      False               False   
3                 False             False      False               False   
4                 False             False      False               False   
..                  ...               ...        ...                 ...   
995               False             False      False               False   
996               False             False      False               False   
997               False             False      False               False   
998               False             False      False               False   
999               False             False      False               False   

     Fraud Flag  Geolocation (Latitude/Longitude)  Device Used  \
0         False                             False        False   
1         False                             False        False   
2         False                             False        False   
3         False                             False        False   
4         False                             False        False   
..          ...                               ...          ...   
995       False                             False        False   
996       False                             False        False   
997       False                             False        False   
998       False                             False        False   
999       False                             False        False   

     Network Slice ID  Latency (ms)  Slice Bandwidth (Mbps)  PIN Code  
0               False         False                   False     False  
1               False         False                   False     False  
2               False         False                   False     False  
3               False         False                   False     False  
4               False         False                   False     False  
..                ...           ...                     ...       ...  
995             False         False                   False     False  
996             False         False                   False     False  
997             False         False                   False     False  
998             False         False                   False     False  
999             False         False                   False     False  

[1000 rows x 14 columns]

In [22]:
df.isnull().any()

Transaction ID                      False
Sender Account ID                   False
Receiver Account ID                 False
Transaction Amount                  False
Transaction Type                    False
Timestamp                           False
Transaction Status                  False
Fraud Flag                          False
Geolocation (Latitude/Longitude)    False
Device Used                         False
Network Slice ID                    False
Latency (ms)                        False
Slice Bandwidth (Mbps)              False
PIN Code                            False
dtype: bool

In [23]:
df.isnull().sum()

Transaction ID                      0
Sender Account ID                   0
Receiver Account ID                 0
Transaction Amount                  0
Transaction Type                    0
Timestamp                           0
Transaction Status                  0
Fraud Flag                          0
Geolocation (Latitude/Longitude)    0
Device Used                         0
Network Slice ID                    0
Latency (ms)                        0
Slice Bandwidth (Mbps)              0
PIN Code                            0
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Transaction ID                    1000 non-null   object 
 1   Sender Account ID                 1000 non-null   object 
 2   Receiver Account ID               1000 non-null   object 
 3   Transaction Amount                1000 non-null   float64
 4   Transaction Type                  1000 non-null   object 
 5   Timestamp                         1000 non-null   object 
 6   Transaction Status                1000 non-null   object 
 7   Fraud Flag                        1000 non-null   bool   
 8   Geolocation (Latitude/Longitude)  1000 non-null   object 
 9   Device Used                       1000 non-null   object 
 10  Network Slice ID                  1000 non-null   object 
 11  Latency (ms)                      1000 non-null   int64  
 12  Slice B

In [25]:
encoder = LabelEncoder()
df["Transaction ID"] = encoder.fit_transform(df["Transaction ID"])
df["Sender Account ID"] = encoder.fit_transform(df["Sender Account ID"])
df["Receiver Account ID"] = encoder.fit_transform(df["Receiver Account ID"])
df["Transaction Type"] = encoder.fit_transform(df["Transaction Type"])
df["Timestamp"] = encoder.fit_transform(df["Timestamp"])
df["Transaction Status"] = encoder.fit_transform(df["Transaction Status"])
df["Fraud Flag"] = encoder.fit_transform(df["Fraud Flag"])
df["Geolocation (Latitude/Longitude)"] = encoder.fit_transform(df["Geolocation (Latitude/Longitude)"])
df["Device Used"] = encoder.fit_transform(df["Device Used"])
df["Network Slice ID"] = encoder.fit_transform(df["Network Slice ID"])

In [26]:
X = df.drop(columns = ["Fraud Flag"])

In [27]:
y = df["Fraud Flag"]

In [28]:
X_train , X_test , y_train , y_test = train_test_split(X , y ,test_size = 0.2 , random_state = 42)

In [29]:
model = SVC(kernel = 'linear')

In [30]:
model.fit(X_train,y_train)

SVC(kernel='linear')

In [31]:
y_pred=model.predict(X_test)

In [32]:
accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
class_report = classification_report(y_test,y_pred)

In [33]:
print("Accuracy : " , accuracy)
print("Confusion Matrix : \n" , conf_matrix)
print("Classification Reoprt : \n" , class_report)

Accuracy :  0.53
Confusion Matrix : 
 [[55 55]
 [39 51]]
Classification Reoprt : 
               precision    recall  f1-score   support

           0       0.59      0.50      0.54       110
           1       0.48      0.57      0.52        90

    accuracy                           0.53       200
   macro avg       0.53      0.53      0.53       200
weighted avg       0.54      0.53      0.53       200



In [34]:
model2 = SVC(kernel = 'poly')

In [35]:
model2.fit(X_train,y_train)

SVC(kernel='poly')

In [36]:
y_pred = model2.predict(X_test)

In [37]:
accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
class_report = classification_report(y_test,y_pred)

In [38]:
print("Accuracy : " , accuracy)
print("Confusion Matrix : \n" , conf_matrix)
print("Classification Reoprt : \n" , class_report)

Accuracy :  0.575
Confusion Matrix : 
 [[97 13]
 [72 18]]
Classification Reoprt : 
               precision    recall  f1-score   support

           0       0.57      0.88      0.70       110
           1       0.58      0.20      0.30        90

    accuracy                           0.57       200
   macro avg       0.58      0.54      0.50       200
weighted avg       0.58      0.57      0.52       200



In [39]:
model3 = SVC(kernel = 'sigmoid')

In [40]:
model3.fit(X_train,y_train)

SVC(kernel='sigmoid')

In [41]:
y_pred = model3.predict(X_test)

In [42]:
accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)
class_report = classification_report(y_test,y_pred)

print("Accuracy : " , accuracy)
print("Confusion Matrix : \n" , conf_matrix)
print("Classification Reoprt : \n" , class_report)

Accuracy :  0.53
Confusion Matrix : 
 [[62 48]
 [46 44]]
Classification Reoprt : 
               precision    recall  f1-score   support

           0       0.57      0.56      0.57       110
           1       0.48      0.49      0.48        90

    accuracy                           0.53       200
   macro avg       0.53      0.53      0.53       200
weighted avg       0.53      0.53      0.53       200

